# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0036_sessionasset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturalobservation',
            name='cultural_feature',
        ),
        migrations.RemoveField(
            model_name='culturalobservation',
            name='ecological_feature',
        ),
        migrations.RemoveField(
            model_name='culturalobservation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='culturalobservation',
            name='industrial_feature',
        ),
        migrations.RemoveField(
            model_name='culturalobservation',
            name='management_feature',
        ),
        migrations.RemoveField(
            model_name='culturalobservation',
            name='marinetraditionalknowledge_ptr',
        ),
        migrations.RemoveField(
            model_name='culturalobservation',
            name='secondary_species',
        ),
        migrations.RemoveField(
            model_name='culturalobservation',
            name='target_species',
        ),
        migrations.RemoveField(
            model_name='culturalobservation',
            name='travel_mode',
        ),
        migrations.RemoveField(
            model_name='culturalobservation',
            name='value_feature',
        ),
        migrations.RemoveField(
            model_name='culturalobservationline',
            name='culturalobservation_ptr',
        ),
        migrations.RemoveField(
            model_name='culturalobservationpoint',
            name='culturalobservation_ptr',
        ),
        migrations.RemoveField(
            model_name='culturalobservationpolygon',
            name='culturalobservation_ptr',
        ),
        migrations.RemoveField(
            model_name='marinetraditionalknowledge',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='marinetraditionalknowledge',
            name='data_entry_id',
        ),
        migrations.RemoveField(
            model_name='marinetraditionalknowledge',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='marinetraditionalknowledge',
            name='harvest_method',
        ),
        migrations.RemoveField(
            model_name='marinetraditionalknowledge',
            name='info_type',
        ),
        migrations.RemoveField(
            model_name='marinetraditionalknowledge',
            name='interview',
        ),
        migrations.RemoveField(
            model_name='marinetraditionalknowledge',
            name='interviewer_id',
        ),
        migrations.RemoveField(
            model_name='marinetraditionalknowledge',
            name='linguistic_group',
        ),
        migrations.RemoveField(
            model_name='marinetraditionalknowledge',
            name='participant_id',
        ),
        migrations.RemoveField(
            model_name='marinetraditionalknowledge',
            name='project',
        ),
        migrations.RemoveField(
            model_name='marinetraditionalknowledge',
            name='seasons',
        ),
        migrations.RemoveField(
            model_name='marinetraditionalknowledge',
            name='shape_type',
        ),
        migrations.RemoveField(
            model_name='marinetraditionalknowledge',
            name='time_frame_end',
        ),
        migrations.RemoveField(
            model_name='marinetraditionalknowledge',
            name='time_frame_start',
        ),
        migrations.RemoveField(
            model_name='marinetraditionalknowledge',
            name='use',
        ),
        migrations.RemoveField(
            model_name='speciesobservation',
            name='ecological_value',
        ),
        migrations.RemoveField(
            model_name='speciesobservation',
            name='fishing_method',
        ),
        migrations.RemoveField(
            model_name='speciesobservation',
            name='marinetraditionalknowledge_ptr',
        ),
        migrations.RemoveField(
            model_name='speciesobservation',
            name='species',
        ),
        migrations.RemoveField(
            model_name='speciesobservation',
            name='species_theme',
        ),
        migrations.RemoveField(
            model_name='speciesobservation',
            name='temporal_trend',
        ),
        migrations.RemoveField(
            model_name='speciesobservationline',
            name='speciesobservation_ptr',
        ),
        migrations.RemoveField(
            model_name='speciesobservationpoint',
            name='speciesobservation_ptr',
        ),
        migrations.RemoveField(
            model_name='speciesobservationpolygon',
            name='speciesobservation_ptr',
        ),
        migrations.DeleteModel(
            name='CulturalObservation',
        ),
        migrations.DeleteModel(
            name='CulturalObservationLine',
        ),
        migrations.DeleteModel(
            name='CulturalObservationPoint',
        ),
        migrations.DeleteModel(
            name='CulturalObservationPolygon',
        ),
        migrations.DeleteModel(
            name='MarineTraditionalKnowledge',
        ),
        migrations.DeleteModel(
            name='SpeciesObservation',
        ),
        migrations.DeleteModel(
            name='SpeciesObservationLine',
        ),
        migrations.DeleteModel(
            name='SpeciesObservationPoint',
        ),
        migrations.DeleteModel(
            name='SpeciesObservationPolygon',
        ),
    ]
