"""
Django settings for cedar project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

from django.core.urlresolvers import reverse_lazy


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from os.path import abspath, basename, dirname
import os

# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DJANGO_ROOT = dirname(dirname(abspath(__file__)))
SITE_ROOT = dirname(DJANGO_ROOT)
SITE_NAME = basename(DJANGO_ROOT)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9^ii$6c)s(bq$0ljqgf*$v2xri6t3gyv1sdv6hn+f2g$52fmw5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'flat',  # Flat theme, needs to go before django.contrib.admin.
    # 'polymorphic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django_hstore',
    'django_extensions',
    'django_filters',
    'easyaudit',
    'braces',
    'djcelery',
    'rest_framework',
    'rest_framework_gis',
    'cryptographic_fields',
    'haystack',
    'leaflet',
    'maps',
    'filer',
    'mptt',
    'taggit',
    'taggit_autosuggest',
    'tags',
    'library.apps.LibraryConfig',
    'cedar',
    'cedar_settings.apps.CedarSettingsConfig',
    'security',
    'reports',
    'geoinfo',
    'actions',
    'heritage',
    'development',
    'crm.apps.CRMConfig',
    'assets.apps.AssetsConfig',
    'help',
    'sanitizer',
    'communication',
    'ecosystems.apps.EcosystemsConfig',
    'communitymap',
    'easy_thumbnails',
    'threadedcomments',
    'django_comments',
    'django.contrib.sites',

)

'''
BEWARE: MIDDLEWARE_CLASSES MAY BE OVERRIDDEN IN settings_local.py if this is a
XML Generating site.
Keep this list here up to date with those in local_settings.py if possible.
'''
MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'easyaudit.middleware.easyaudit.EasyAuditMiddleware',
    'development.middleware.RestrictAccessMiddleware'
    # 'cedar.middleware.AnonymousXMLGeneratorAccessMiddleware'
)

ROOT_URLCONF = 'cedar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(DJANGO_ROOT, 'cedar/templates/registration'),  # Auth expects the login template to be in a folder named registration.
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cedar.context_processors.is_haida',
            ],
        },
    },
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}

WSGI_APPLICATION = 'cedar.wsgi.application'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'cedar_verbose': {
            'format': "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt': "%d/%b/%Y %H:%M:%S"
        },
        'cedar_simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'handler_for_communication': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(SITE_ROOT, 'logs', 'communication_debug.log'),

            # Rotation is handled by /etc/logrotate.d/django-cedar
            # 'class': 'logging.handlers.RotatingFileHandler',
            # 'maxBytes': 1024 * 1024 * 20,  # 20 MB
            # 'backupCount': 5,
            # 'filename': os.path.join(SITE_ROOT, 'logs', 'communication_debug.log'),
            'formatter': 'cedar_verbose'
        },
    },
    'loggers': {
        'communication': {
            'handlers': ['handler_for_communication'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# This doesn't work for me for some reason. I have to override it in my local settings to
# STATIC_URL = '/static-badger/' or literally any folder name other than '/static/'. -- Hugh

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

# django-filer settings.
# Prevent all staff from uploading and managing files and images:
# FILER_ENABLE_PERMISSIONS = True # this seems like a mistake.

# Prevent downloading of files and images by anyone who guesses the URL. Requires a change to urls.py:
FILER_ENABLE_PERMISSIONS = True
# Include the images/files themselves in dumpdata output, so that they can be re-deployed with loaddata:
FILER_DUMP_PAYLOAD = False

THUMBNAIL_ALIASES = {
    '': {
        'detail': {'size': (500, 300), 'crop': 'scale'},
        'avatar': {'size': (50, 50), 'crop': 'crop'},
        'card': {'size': (696, 500), 'crop': 'crop'},
    },
}

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissions'
    ],
    'DEFAULT_FILTER_BACKENDS': ('rest_framework.filters.DjangoFilterBackend',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
}

LOGIN_URL = '/login/'

# LOGIN_REDIRECT_URL = reverse_lazy('heritage:dashboard')
LOGIN_REDIRECT_URL = 'home'

# PHONENUMBER_DEFAULT_FORMAT = 'NATIONAL'
PHONENUMBER_DEFAULT_FORMAT = 'INTERNATIONAL'
PHONENUMBER_DEFAULT_REGION = 'CA'           # allows user to input north american number without country code.

# HAYSTACK_CONNECTIONS = {} # Goes in private settings
HAYSTACK_CUSTOM_HIGHLIGHTER = 'assets.search_utils.DocumentTextHighlighter'
# HAYSTACK_SEARCH_RESULTS_PER_PAGE = 20     # Now exists as a cedar_setting in assets.

# oauth2client django_utils settings
# Putting random warblegarble in these settings so oauth2client doesn't break everything if they aren't set.
# If using gmail with mailharvest, add actual files in settings_local.py
GOOGLE_OAUTH2_CLIENT_ID = "#######################################.apps.googleusercontent.com"
GOOGLE_OAUTH2_CLIENT_SECRET = "######################"

GOOGLE_OAUTH2_SCOPES = ['https://mail.google.com/', 'https://www.googleapis.com/auth/userinfo.email']

# Celery settings
CELERY_RESULT_BACKEND = "djcelery.backends.database:DatabaseBackend"
CELERY_SEND_EVENTS = True
# where to store periodic tasks (needed for scheduler)
CELERYBEAT_SCHEDULER = "djcelery.schedulers.DatabaseScheduler"
CELERY_TASK_RESULT_EXPIRES = 7*86400    # 7 days

COMMENTS_APP = 'threadedcomments'

# Taggit autosuggest settings:   https://bitbucket.org/fabian/django-taggit-autosuggest
TAGGIT_AUTOSUGGEST_MODELS = {
    'default': 'tags.Tag',
    'tags.Tag': ('tags', 'Tag'),
    'library.CollectionTag': ('library', 'CollectionTag'),
    'library.CaseBriefTag': ('library', 'CaseBriefTag'),
    'library.PersonMentionedTag': ('library', 'PersonMentionedTag'),
    'ecosystems.PlantTag': ('ecosystems', 'PlantTag'),
    'ecosystems.AnimalTag': ('ecosystems', 'AnimalTag'),
    'heritage.GazetteerNameTag': ('heritage', 'GazetteerNameTag'),
}
TAGGIT_AUTOSUGGEST_MAX_SUGGESTIONS = None


LEAFLET_CONFIG = {
    'DEFAULT_CENTER': [51.0, -126.0],
    'DEFAULT_ZOOM': 8,
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 18,
    'RESET_VIEW': False,
    'TILES': [  # Override the default tiles because they cause issues being json serialized.
        ['OSM', '//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', '© <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'],
    ],
    'PLUGINS': {
        'fullscreen': {
            'css': 'bower_components/leaflet.fullscreen/Control.FullScreen.css',
            'js': 'bower_components/leaflet.fullscreen/Control.FullScreen.js',
            'auto-include': True,
        },
        'leaflet-awesome-fork': {
            'css': 'lib/Leaflet.awesome-markers-2.0-fork/dist/leaflet.awesome-markers.css',
            'js': 'lib/Leaflet.awesome-markers-2.0-fork/dist/leaflet.awesome-markers.min.js',
            'auto-include': True,
        },
        'font-awesome': {
            'css': 'bower_components/font-awesome/css/font-awesome.min.css',
            'auto-include': True,
        },
        'map-style-helper': {
            'js': 'maps/js/map_styler.js',
            'css': 'maps/css/maps.css',
            'auto-include': True
        },
        'markercluster': {
            'css': ['bower_components/leaflet.markercluster/dist/MarkerCluster.css', 'bower_components/leaflet.markercluster/dist/MarkerCluster.Default.css'],
            'js': 'bower_components/leaflet.markercluster/dist/leaflet.markercluster.js',
            'auto-include': True
        },
        'sidebar-v2': {
            'css': 'bower_components/sidebar-v2/css/leaflet-sidebar.min.css',
            'js': 'bower_components/sidebar-v2/js/leaflet-sidebar.min.js',
            'auto-include': True
        }
    },
}


SITE_ID = 1

DJANGO_EASY_AUDIT_UNREGISTERED_CLASSES_EXTRA = [
    'djcelery.taskmeta',
    'djcelery.periodictask',
    'communication.harvesthistory',
]

ALLOWED_HTML_TAGS = ['div', 'span', 'a', 'em', 'strong', 'cite', 'code', 'ol', 'ul', 'li', 'dl', 'dt', 'dd', 'p', 'br',
                     'img', 'hr', 'h1', 'h2', 'h3', 'fn', 'table', 'thead', 'th', 'tr', 'td', 'u', 'strike', 'sup',
                     'sub', 'abbr', 'acronym']

ALLOWED_HTML_ATTRIBUTES = {
    '*': ['style'],  # Allow style attributes on everything.
    'a': ['href', 'title'],
    'abbr': ['title'],
    'acronym': ['title'],
    'img': ['width', 'height'],
}

ALLOWED_HTML_STYLES = ['color', 'background', 'background-color', 'font-size', 'font-weight', 'height', 'width']
